name: Release Caça aos Peixes

on:
  workflow_dispatch: # permite disparar manualmente
  push:
    tags:
      - "v*.*.*" # dispara quando você fizer git tag vX.Y.Z

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Empacotar versão Windows
        run: |
          cd caca-aos-peixes-v1.0.2
          zip -r ../caca-aos-peixes-windows.zip .
      
      - name: Empacotar versão Linux
        run: |
          cd caca-aos-peixes-GNU-Version
          tar -czf ../caca-aos-peixes-linux.tar.gz .

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            caca-aos-peixes-windows.zip
            caca-aos-peixes-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
